### ISSUE TITLE
Add `/permissions` endpoint

### ISSUE THREAD

**Issue by nglgzz** [kiwicom/iam#121]
This is the first step for #93.

My proposal for the endpoint is to accept a mandatory `services` parameter, and an optional `user` parameter. If `user` is specified, the user permissions for the specified services will be returned; otherwise, all permissions will be returned, each with a list of user IDs having that permission. 

### Get all permissions 

```
GET /v1/permissions?services=service1,service2

{
  "service1": {
    "access": [<list of IDs>],
    "admin.access": [<list of IDs>],
    "other rule": [<list of IDs>]
  }, 
  "service2": {}
}
```

### Get user permissions 

```
GET /v1/permissions?services=service1,service2&user=jane.doe@example.com

{
  "service1": ["access", "other rule"],
  "service2": [],
}
```

**Comment by fallion** [comment]
@kiwicom/kiwi-iam-core plz go over this

**Comment by fallion** [comment]
@nglgzz I guess this requires defining what the primary ID is. Currently we use only e-mail.

**Comment by nglgzz** [comment]
Currently for caching permissions we use `EmployeeNumber` (int)  as the primary ID, so we could probably use that. Maybe it would make more sense to change the second request to use this ID as well. What about this?

```
GET /v1/permissions?services=service1,service2&employeeNumber=1234
```
