### ISSUE TITLE
Cache versioning

### ISSUE THREAD

**Issue by fallion** [kiwicom/iam#152]
Currently we face problems when upgrading to new versions of how we handle the cache, resulting in having to manually wipe the cache or having to adjust the time until next cache reset.

**Proposed solution:**
`internal/storage/redis_cache.go` gets a new field in struct for version. This version can be adjusted when breaking changes are needed to be applied. The version will be appended to the cache.

`user` -> `user-v1` etc.

**Alternatives:**
- each user of the cache will send the adjusted key itself
- create endpoint to wipe cache via API (needs to be highly secure)

**Comment by nglgzz** [comment]
I think the proposed solution is the most elegant one.

Where do you see us setting the value for this version field? Should we hard-code it in the `redis_cache` file, or will it be passed to the `NewRedisCache` method when initializing the cache?

**Comment by fallion** [comment]
I think it would be better to pass it in when initialising, alternatively every user can pass its own version in, but that will hide it in more places.

**Comment by fallion** [comment]
Closed by #154
