### ISSUE TITLE
Create more detailed README

### ISSUE THREAD

**Issue by matoous** [kiwicom/iam#202]
This project is public and as such should describe what and how it is doing. Currently the README isn't of much use of external entities. We should add paragraph describing Kiwi IAM in short and more detailed description of the authentication/authorization flow later in the README.

**Comment by fallion** [comment]
The readme should be moved to the Hugo pages which are ready for this project. Readme should be updated to point to them.

**Comment by matoous** [comment]
Cool, didn't know about that. Do you have a link to the repo with hugo pages?

**Comment by fallion** [comment]
They’re in the www folder in this repo.
