### ISSUE TITLE
[proposal] Okta Terraform

### ISSUE THREAD

**Issue by fallion** [kiwicom/iam#29]
IAM should be able to generate Okta Terraform compliant code in order to ease usage with terraform.

This feature needs to fulfil the following:
- [ ] create terraform code
- [ ] edit existing terraform code
- [ ] connect to private Gitlab
- [ ] create merge request on behalf of user who submitted the request
- [ ] fill merge request info describing why this change is requested

**Comment by janmasarik** [comment]
I would change the requirements to the following (especially for the first iteration of the App):
- [ ] create terraform code
- [ ] give suggestions (dropdown) taken for Okta (e.g. for department)

**Comment by fallion** [comment]
@janmasarik Is this now superseded by the Terraform module?

**Comment by janmasarik** [comment]
For now yes. With the current module, readability dramatically improved, so
it is not a prio anymore.
