### ISSUE TITLE
Add Drone CI

### ISSUE THREAD

**Issue by fallion** [kiwicom/iam#3]
Gitlab CI was removed due to the migration to Github. Drone will be used going forward in this repo.

**Comment by nglgzz** [comment]
We won't be able to use Drone as docker-in-docker doesn't seem to work there, and we need that feature to run docker-compose for end to end tests. 

Will try using CircleCI.

**Comment by nglgzz** [comment]
Solved with https://github.com/kiwicom/iam/pull/18
